name: Publish NPM Package

on:
  release:
    types: [created, published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Debug Event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event type: ${{ github.event.action }}"
          echo "Ref: ${{ github.ref }}"
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Debug Package Version
        run: |
          echo "Package version from package.json:"
          cat package.json | grep version
          echo "Git ref: ${{ github.ref }}"
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
